"""Corregir relaciones entre Pareja, Jugador y Campeonato

Revision ID: 01d7e0ee8c32
Revises: 426beea20cd1
Create Date: 2024-10-23 11:02:29.041681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d7e0ee8c32'
down_revision: Union[str, None] = '426beea20cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parejas', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_parejas_nombre'), 'parejas', ['nombre'], unique=False)
    op.drop_column('parejas', 'club')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parejas', sa.Column('club', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_parejas_nombre'), table_name='parejas')
    op.alter_column('parejas', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
