"""Añadir columna activa a parejas

Revision ID: 32a7cb9df2d1
Revises: 
Create Date: 2024-09-20 10:45:27.773541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a7cb9df2d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jugadores', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jugadores', 'apellido',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_jugadores_nombre', table_name='jugadores')
    op.create_unique_constraint('uq_jugador', 'jugadores', ['nombre', 'apellido'])
    op.drop_constraint('jugadores_campeonato_id_fkey', 'jugadores', type_='foreignkey')
    op.drop_column('jugadores', 'campeonato_id')
    op.add_column('parejas', sa.Column('activa', sa.Boolean(), nullable=True))
    op.alter_column('parejas', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_parejas_nombre', table_name='parejas')
    op.drop_column('parejas', 'club')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parejas', sa.Column('club', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_parejas_nombre', 'parejas', ['nombre'], unique=False)
    op.alter_column('parejas', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('parejas', 'activa')
    op.add_column('jugadores', sa.Column('campeonato_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('jugadores_campeonato_id_fkey', 'jugadores', 'campeonatos', ['campeonato_id'], ['id'])
    op.drop_constraint('uq_jugador', 'jugadores', type_='unique')
    op.create_index('ix_jugadores_nombre', 'jugadores', ['nombre'], unique=False)
    op.alter_column('jugadores', 'apellido',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jugadores', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
