"""Update pareja and jugador models

Revision ID: 3b242be87e0f
Revises: c1a0980330f8
Create Date: 2024-10-23 12:26:32.533301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b242be87e0f'
down_revision: Union[str, None] = 'c1a0980330f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jugadores', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jugadores', 'apellido',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jugadores', 'campeonato_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_jugadores_apellido'), 'jugadores', ['apellido'], unique=False)
    op.create_index(op.f('ix_jugadores_nombre'), 'jugadores', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jugadores_nombre'), table_name='jugadores')
    op.drop_index(op.f('ix_jugadores_apellido'), table_name='jugadores')
    op.alter_column('jugadores', 'campeonato_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jugadores', 'apellido',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jugadores', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
