"""Agregar campeonato_id a Resultado y Pareja

Revision ID: 89ced385cfa5
Revises: 86926057be4b
Create Date: 2024-10-16 12:41:01.048096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ced385cfa5'
down_revision: Union[str, None] = '86926057be4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mesas_campeonato_id_fkey', 'mesas', type_='foreignkey')
    op.drop_column('mesas', 'campeonato_id')
    op.alter_column('parejas', 'campeonato_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('resultados', sa.Column('campeonato_id', sa.Integer(), nullable=True))
    op.execute("UPDATE resultados SET campeonato_id = 1")
    op.alter_column('resultados', 'campeonato_id', nullable=False)
    op.create_foreign_key(None, 'resultados', 'campeonatos', ['campeonato_id'], ['id'])
    
    # Para la tabla parejas
    op.execute("UPDATE parejas SET campeonato_id = 1")
    
    # Para la tabla jugadores
    op.add_column('jugadores', sa.Column('campeonato_id', sa.Integer(), nullable=True))
    
    # Establecer el valor 1 para todos los registros existentes
    op.execute("UPDATE jugadores SET campeonato_id = 1")
    
    # Cambiar la columna a NOT NULL
    op.alter_column('jugadores', 'campeonato_id', nullable=False)
    
    # Crear la clave foránea
    op.create_foreign_key(None, 'jugadores', 'campeonatos', ['campeonato_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resultados', type_='foreignkey')
    op.drop_column('resultados', 'campeonato_id')
    op.drop_constraint(None, 'jugadores', type_='foreignkey')
    op.drop_column('jugadores', 'campeonato_id')
    op.alter_column('parejas', 'campeonato_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('mesas', sa.Column('campeonato_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('mesas_campeonato_id_fkey', 'mesas', 'campeonatos', ['campeonato_id'], ['id'])
    # ### end Alembic commands ###

