"""Add Resultado table

Revision ID: aa9324bf1f0c
Revises: 32a7cb9df2d1
Create Date: 2024-10-10 11:43:15.936615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9324bf1f0c'
down_revision: Union[str, None] = '32a7cb9df2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campeonatos', 'inscripcion_cerrada')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campeonatos', sa.Column('inscripcion_cerrada', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
