"""Añadir columna club a Pareja

Revision ID: c1a0980330f8
Revises: 01d7e0ee8c32
Create Date: 2024-10-23 11:08:59.657889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a0980330f8'
down_revision: Union[str, None] = '01d7e0ee8c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parejas', sa.Column('club', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parejas', 'club')
    # ### end Alembic commands ###
