"""add campeonato_id to mesas

Revision ID: d708c2ff2d38
Revises: e10903c3fefc
Create Date: 2024-10-16 14:49:25.523096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd708c2ff2d38'
down_revision: Union[str, None] = 'e10903c3fefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jugadores_campeonato_id_fkey', 'jugadores', type_='foreignkey')
    op.drop_column('jugadores', 'campeonato_id')
    op.add_column('mesas', sa.Column('campeonato_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mesas', 'campeonatos', ['campeonato_id'], ['id'])
    op.alter_column('parejas', 'campeonato_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('resultados_campeonato_id_fkey', 'resultados', type_='foreignkey')
    op.drop_column('resultados', 'campeonato_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultados', sa.Column('campeonato_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('resultados_campeonato_id_fkey', 'resultados', 'campeonatos', ['campeonato_id'], ['id'])
    op.alter_column('parejas', 'campeonato_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'mesas', type_='foreignkey')
    op.drop_column('mesas', 'campeonato_id')
    op.add_column('jugadores', sa.Column('campeonato_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('jugadores_campeonato_id_fkey', 'jugadores', 'campeonatos', ['campeonato_id'], ['id'])
    # ### end Alembic commands ###
