"""Añadir campeonato_id a la tabla jugadores

Revision ID: e10903c3fefc
Revises: 89ced385cfa5
Create Date: 2024-10-16 13:00:00.715208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10903c3fefc'
down_revision: Union[str, None] = '89ced385cfa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jugadores', sa.Column('campeonato_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jugadores', 'campeonatos', ['campeonato_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jugadores', type_='foreignkey')
    op.drop_column('jugadores', 'campeonato_id')
    # ### end Alembic commands ###
