"""renombrar_columnas_ranking_final

Revision ID: f6c820e16ef0
Revises: 10b05350d6c1
Create Date: 2024-10-30 11:54:58.466817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c820e16ef0'
down_revision: Union[str, None] = '10b05350d6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
